field: f4696807-fad3-4e93-a26a-e1946637d383
fieldLayouts:
  17e44b1b-29eb-4b2d-af27-7cabc3c1ac4a:
    tabs:
      -
        elements:
          -
            fieldUid: 1a3b8507-a4a7-472b-9b10-e99f057d5cd6
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b0d7dcf1-30a9-4fb9-90ba-3fdf5927e19c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1a3b8507-a4a7-472b-9b10-e99f057d5cd6:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: '1'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b0d7dcf1-30a9-4fb9-90ba-3fdf5927e19c:
    contentColumnType: text
    fieldGroup: null
    handle: citation
    instructions: ''
    name: Citation
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: blockquote
name: Blockquote
sortOrder: 2
