field: f4696807-fad3-4e93-a26a-e1946637d383
fieldLayouts:
  ae2817ec-1083-4a4d-b4bb-0a2d71acac2c:
    tabs:
      -
        elements:
          -
            fieldUid: c5a9f115-5b57-497d-9a9f-c76ef6a8881e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c5a9f115-5b57-497d-9a9f-c76ef6a8881e:
    contentColumnType: text
    fieldGroup: null
    handle: textContent
    instructions: ''
    name: Content
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: '1'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 1
