contentColumnType: text
fieldGroup: f445487e-f6a2-471c-a08b-3096f57da2d0
handle: linkUrl
instructions: ''
name: 'Link URL'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
